<a href="https://colab.research.google.com/github/ompang222/deep-learning/blob/main/inclass/2024_03_13_deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 텐서플로 훑어보기

In [12]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32, shape=3)
b = tf.Variable(3)
c = tf.add(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(c, {a: [1,2,3]}))

[4 5 6]


In [7]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.multiply(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(c, {a: [[1,2,3], [1,2,3], [1,2,3]], b: [[1,2,3], [1,2,3], [1,2,3]]}))


[[1 4 9]
 [1 4 9]
 [1 4 9]]


In [16]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.placeholder(tf.float32)
d = tf.placeholder(tf.float32)

add0peration = tf.add(a,b)
minus0peration = tf.subtract(a,b)
mul0peration = tf.multiply(a,b)
div0peration = tf.div(c,d)


init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print("Plus =>", sess.run(add0peration, {a: [[1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
  print("Mnius =>", sess.run(minus0peration, {a: [[1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
  print("Multiply =>", sess.run(mul0peration, {a: [[1,2,3], [1,2,3]], b: [[5,2,3], [1,2,3]]}))
  print("Div =>", sess.run(div0peration, {c: [[1,2,3], [1,2,3]], d: [[5,2,3], [1,2,3]]}))

Plus => [[6 4 6]
 [2 4 6]]
Mnius => [[-4  0  0]
 [ 0  0  0]]
Multiply => [[5 4 9]
 [1 4 9]]
Div => [[0.2 1.  1. ]
 [1.  1.  1. ]]


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(c, {a: [[1,2,3], [1,2,3], [1,2,3]], b: [[1,2,3], [1,2,3], [1,2,3]]}))